// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0xz7Eb-Xo2zugk4qYwK0UTB_Jw2OBp_g',
    appId: '1:184809195338:web:3dea5d6a9908bd1b9ee3b3',
    messagingSenderId: '184809195338',
    projectId: 'habit-tracker-b0206',
    authDomain: 'habit-tracker-b0206.firebaseapp.com',
    storageBucket: 'habit-tracker-b0206.firebasestorage.app',
    measurementId: 'G-Z0Z652DPPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTYRsl6CG3lg9xsS31cwIMbsSfCVCMjCI',
    appId: '1:184809195338:android:03275e6eb82d21b19ee3b3',
    messagingSenderId: '184809195338',
    projectId: 'habit-tracker-b0206',
    storageBucket: 'habit-tracker-b0206.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgg1FSArie8WtqOvuewCZ2HEkaYpkzjQw',
    appId: '1:184809195338:ios:ccb9c7363ae2b4579ee3b3',
    messagingSenderId: '184809195338',
    projectId: 'habit-tracker-b0206',
    storageBucket: 'habit-tracker-b0206.firebasestorage.app',
    androidClientId:
        '184809195338-d0s09nol0j4qeeutbd3sc4pdnvdvbvr4.apps.googleusercontent.com',
    iosClientId:
        '184809195338-ml8r9i46vvnt4h4n5b11rb1lenhl9k78.apps.googleusercontent.com',
    iosBundleId: 'com.example.habit',
  );
}
